server:
  port: 8080

spring:
  application:
    name: zsxq-sdk-demo

zsxq:
  token: ${ZSXQ_TOKEN:8D0689E0-C534-4673-BDF4-B4DE4B9C55C1_C7FC4C169922C77C}
  group-id: ${ZSXQ_GROUP_ID:51115214421144}
  timeout: 10000
  retry-count: 3
  retry-delay: 1000
